// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMYErVa_SsPvEBcF4HGidA8Lgoblbz7iA',
    appId: '1:905528678731:web:b2ec1351b28a5b14e6f0ce',
    messagingSenderId: '905528678731',
    projectId: 'authfirebasetp',
    authDomain: 'authfirebasetp.firebaseapp.com',
    storageBucket: 'authfirebasetp.appspot.com',
    measurementId: 'G-2BMDD5VP6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7CaIkRwfrSmkMLhodeBL7C3bQXnixKjo',
    appId: '1:905528678731:android:2c86e64aa736df9de6f0ce',
    messagingSenderId: '905528678731',
    projectId: 'authfirebasetp',
    storageBucket: 'authfirebasetp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgj_FQotLXhXaSa4AqVdQWxfFx2571GM8',
    appId: '1:905528678731:ios:a31a4125b7c0d369e6f0ce',
    messagingSenderId: '905528678731',
    projectId: 'authfirebasetp',
    storageBucket: 'authfirebasetp.appspot.com',
    iosClientId:
        '905528678731-ssneh713dq254gcdanpe0nviuto6m0vv.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFirebaseTp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgj_FQotLXhXaSa4AqVdQWxfFx2571GM8',
    appId: '1:905528678731:ios:a31a4125b7c0d369e6f0ce',
    messagingSenderId: '905528678731',
    projectId: 'authfirebasetp',
    storageBucket: 'authfirebasetp.appspot.com',
    iosClientId:
        '905528678731-ssneh713dq254gcdanpe0nviuto6m0vv.apps.googleusercontent.com',
    iosBundleId: 'com.example.authFirebaseTp',
  );
}
